const actionTypes = {
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',

  CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  CREATE_USER_ERROR: 'CREATE_USER_ERROR',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',

  RESET_CREATE_USER: 'RESET_CREATE_USER',

  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_ERROR: 'DELETE_USER_ERROR',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',

  RESET_DELETE_USER: 'RESET_DELETE_USER',

};

export default actionTypes;
